layout_spectrum: 0.2956989
color:
  saturation: 0.7626814
  lightness: 0.03154132
  brandStrength: 0.3413191
  rhythmicContrast: 0.3308548
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
typography_spectrum: 0.6275591
name: Miele Sleeps
