name: Miele Sleeps
favicon: null
layout_spectrum: 0.50275
typography_spectrum: 0.6275591
title: Miele Sleeps
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.3413191
  lightness: 0.03154132
  saturation: 0.7626814
  rhythmicContrast: 0.3308548
purpose: []
